package ModdleEntity;
// Generated May 10, 2020 9:00:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name="Book"
    ,catalog="Library"
)
public class Book  implements java.io.Serializable {


     private String bookId;
     private String bookTitle;
     private String publishingHouse;
     private Date dateOfPublication;
     private String author;
     private int pages;
     private String categoryId;

    public Book() {
    }

    public Book(String bookId, String bookTitle, String publishingHouse, Date dateOfPublication, String author, int pages, String categoryId) {
       this.bookId = bookId;
       this.bookTitle = bookTitle;
       this.publishingHouse = publishingHouse;
       this.dateOfPublication = dateOfPublication;
       this.author = author;
       this.pages = pages;
       this.categoryId = categoryId;
    }
   
     @Id 

    
    @Column(name="bookId", unique=true, nullable=false, length=20)
    public String getBookId() {
        return this.bookId;
    }
    
    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    
    @Column(name="bookTitle", nullable=false, length=20)
    public String getBookTitle() {
        return this.bookTitle;
    }
    
    public void setBookTitle(String bookTitle) {
        this.bookTitle = bookTitle;
    }

    
    @Column(name="publishingHouse", nullable=false, length=20)
    public String getPublishingHouse() {
        return this.publishingHouse;
    }
    
    public void setPublishingHouse(String publishingHouse) {
        this.publishingHouse = publishingHouse;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateOfPublication", nullable=false, length=10)
    public Date getDateOfPublication() {
        return this.dateOfPublication;
    }
    
    public void setDateOfPublication(Date dateOfPublication) {
        this.dateOfPublication = dateOfPublication;
    }

    
    @Column(name="author", nullable=false, length=20)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    
    @Column(name="pages", nullable=false)
    public int getPages() {
        return this.pages;
    }
    
    public void setPages(int pages) {
        this.pages = pages;
    }
    
    @Column(name="categoryId")
    public String getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }
    




}


