package ModdleEntity;
// Generated May 13, 2020 9:28:36 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BookCategory generated by hbm2java
 */
@Entity
@Table(name="book_category"
    ,catalog="Library"
)
public class BookCategory  implements java.io.Serializable {


     private String categoryId;
     private String categoryName;

    public BookCategory() {
    }

    public BookCategory(String categoryId, String categoryName) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
    }
   
     @Id 

    
    @Column(name="category_Id", unique=true, nullable=false, length=10)
    public String getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="category_Name", nullable=false, length=30)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }




}


