package ModdleEntity;
// Generated May 13, 2020 9:28:36 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="Client"
    ,catalog="Library"
)
public class Client  implements java.io.Serializable {


     private String regNo;
     private String clientCategory;
     private String emailAddress;
     private String firstName;
     private String lastName;
     private String phoneNumber;
     private byte[] photo;

    public Client() {
    }

    public Client(String regNo, String clientCategory, String emailAddress, String firstName, String lastName, String phoneNumber, byte[] photo) {
       this.regNo = regNo;
       this.clientCategory = clientCategory;
       this.emailAddress = emailAddress;
       this.firstName = firstName;
       this.lastName = lastName;
       this.phoneNumber = phoneNumber;
       this.photo = photo;
    }
   
     @Id 

    
    @Column(name="regNo", unique=true, nullable=false, length=8)
    public String getRegNo() {
        return this.regNo;
    }
    
    public void setRegNo(String regNo) {
        this.regNo = regNo;
    }

    
    @Column(name="clientCategory", nullable=false, length=20)
    public String getClientCategory() {
        return this.clientCategory;
    }
    
    public void setClientCategory(String clientCategory) {
        this.clientCategory = clientCategory;
    }

    
    @Column(name="emailAddress", nullable=false, length=20)
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    
    @Column(name="firstName", nullable=false, length=20)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="lastName", nullable=false, length=20)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="phoneNumber", nullable=false, length=20)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="photo", nullable=false, columnDefinition="blob")
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }




}


