package ModdleEntity;
// Generated May 10, 2020 9:00:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Operations generated by hbm2java
 */
@Entity
@Table(name="operations"
    ,catalog="Library"
)
public class Operations  implements java.io.Serializable {


     private String firstName;
     private String bookName;
     private Date dateTime;
     private String status;
     private String operationCategory;

    public Operations() {
    }

    public Operations(String firstName, String bookName, Date dateTime, String status, String operationCategory) {
       this.firstName = firstName;
       this.bookName = bookName;
       this.dateTime = dateTime;
       this.status = status;
       this.operationCategory = operationCategory;
    }
   
     @Id 

    
    @Column(name="firstName", unique=true, nullable=false, length=100)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="bookName", nullable=false, length=20)
    public String getBookName() {
        return this.bookName;
    }
    
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateTime", nullable=false, length=10)
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    
    @Column(name="status", nullable=false, length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="operationCategory", nullable=false, length=40)
    public String getOperationCategory() {
        return this.operationCategory;
    }
    
    public void setOperationCategory(String operationCategory) {
        this.operationCategory = operationCategory;
    }




}


